name: Test Action

on: [push]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    environment: main
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::531249009620:role/Deploy
          aws-region: eu-west-1
      - uses: ./
        with:
          policies: tests/data/policy_checks/policies/
          results: results
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results
